name: Run container spec 

on:
  push:
    branches:
      - container
  pull_request:
    branches:
      - container
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
     - uses: actions/checkout@v4
       with:
         ref: container
     - name: Install OPAM
       uses: ocaml/setup-ocaml@v3
       with:
         ocaml-compiler: 4.13.1  
         allow-prerelease-opam: true
          
     - name: Initialize OPAM environment
       run: |
          opam init -y --disable-sandboxing
          eval $(opam env)
     - name: Install Coq 8.16.1
       run: |
          opam update
          opam install -j 3 -y coq.8.16.1
          echo "eval $(opam env)" >> $GITHUB_ENV
     - run: cd ${{ github.workspace }}/container/coq
     - run: |
          eval $(opam env)
          cd ${{ github.workspace }}/container/coq/LayerSem
          pwd
          make -j7
          export COQPATH=${{ github.workspace }}/container/coq:
          cd ${{ github.workspace }}/container/coq/revising
          pwd
          make